language: node_js
node_js:
  - 10

branches:
  only:
    - master

script:
  - npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
